# Generated by Django 3.1.2 on 2020-11-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_number', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='system_user',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('system_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banking.system_user')),
            ],
            bases=('banking.system_user',),
        ),
        migrations.CreateModel(
            name='payee_account',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banking.account')),
            ],
            bases=('banking.account',),
        ),
        migrations.CreateModel(
            name='payer_account',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banking.account')),
            ],
            bases=('banking.account',),
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('system_user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banking.system_user')),
                ('residential_address', models.CharField(max_length=100)),
                ('identification_information', models.CharField(max_length=100)),
            ],
            bases=('banking.system_user',),
        ),
        migrations.CreateModel(
            name='wire_trasfer',
            fields=[
                ('wt_transaction_no', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('currency_type', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=False)),
                ('payee_name', models.CharField(max_length=100)),
                ('payee_bank_name', models.CharField(max_length=100)),
                ('payee_account_no', models.CharField(max_length=100)),
                ('payee_swift_code', models.CharField(max_length=100)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.account')),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.operator')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('amount', models.IntegerField(default=0)),
                ('purpose', models.CharField(max_length=10)),
                ('payee_account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.payee_account')),
                ('payer_account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.payer_account')),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('loan_application_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.account')),
                ('opreator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.operator')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='operator_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.operator'),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.user'),
        ),
    ]
